Remove Fatal Warnings in Shellfish
davenverse/shellfish pull request #66
Opened 2024-06-07 17:47 UTC by Hombre-x

This PR removes the different warnings that made the compiler crash under the flag `tlFatalWarnings`.

What was done:
- Before most of the Paths were defined in terms of Java NIO Paths, which caused many Fs2 methods to show a warning as the usage with paths other than Fs2's owns is outdated. As a result, the majority of the API was migrated using the `Files[F]` typeclass (except for one method that still uses `JFiles` and I couldn't find a replacement to that method just yet).

- Replaced old `utf8Encode` and `utf8Decode` to its new variants, `utf8.encode` and `utf8.decode` respectively.

- Removed unused imports 

- Removed the flag `tlFatalWarnings` in `build.sbt`

2024-06-07 21:53 UTC, TonioGela commented on core/src/main/scala/io/chrisdavenport/shellfish/Shell.scala
> +        _  <- files.createSymbolicLink(r1, r2)
you also solved a bug here :D

2024-06-08 11:18 UTC, zetashift commented on examples/src/main/scala/io/chrisdavenport/shellfish/Main.scala
> +    // val p = SubProcess.io
```suggestion

```

2024-06-09 13:31 UTC, TonioGela approved these changes
LGTM

2024-06-10 06:24 UTC, lenguyenthanh requested changes
There is only one issue with `touch` function and I just have some code suggestions including code golfing. Otherwise LGTM. Great job @Hombre-x 🎉

2024-06-10 06:24 UTC, lenguyenthanh commented on core/src/main/scala/io/chrisdavenport/shellfish/Shell.scala
> +            creationTime = Some(now),
```suggestion
            creationTime = None,
```
I believe We should use `None` here, as `touch` only modifies last modified time.

2024-06-10 06:24 UTC, lenguyenthanh commented on core/src/main/scala/io/chrisdavenport/shellfish/Shell.scala
> +                if (s.fileName == Path(path)) s.toString.some else None
```suggestion
                Option.when(s.fileName == Path(path))(s.toString)
```

2024-06-10 06:24 UTC, lenguyenthanh commented on core/src/main/scala/io/chrisdavenport/shellfish/Shell.scala
> +                .map(isExe => (p, isExe && p.fileName == Path(path)))
```suggestion
            .evalMap(p =>
              files.isExecutable(p)
                .map(isExe => (p, isExe && p.fileName == Path(path)))
```

2024-06-10 06:24 UTC, lenguyenthanh commented on core/src/main/scala/io/chrisdavenport/shellfish/Shell.scala
> +            .map(_._1.toString)
```suggestion
            .collect {
              case x if x._2 => x._1.toString
            }
```
`filter.map == collect`

2024-06-10 18:33 UTC, Hombre-x commented
The changes are done!

2024-06-11 00:24 UTC, lenguyenthanh approved these changes
LGTM

2024-06-11 06:44 UTC, merged